# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian10"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "web_vagrant_vm"
    vb.memory = "512"
  end
  
  config.vm.provision "file", run: "always", source: "./01-demosite-php/index.php", destination: "/home/vagrant/01-demosite-php/index.php"
  config.vm.provision "file", run: "always", source: "./01-demosite-static/index.html", destination: "/home/vagrant/01-demosite-static/index.html"
  config.vm.provision "file", run: "always", source: "./ports.conf", destination: "/home/vagrant/apache2/ports.conf"
  config.vm.provision "file", run: "always", source: "./000-default.conf", destination: "/home/vagrant/sites-available/000-default.conf"
  
    config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y apache2
	apt-get install -y php libapache2-mod-php
	mkdir -p /var/www/01-demosite-php
	mkdir -p /var/www/01-demosite-static
    cp /home/vagrant/01-demosite-php/index.php /var/www/01-demosite-php
	cp /home/vagrant/01-demosite-static/index.html /var/www/01-demosite-static
	cp /home/vagrant/apache2/ports.conf /etc/apache2
	cp /home/vagrant/sites-available/000-default.conf /etc/apache2/sites-available
	systemctl restart apache2
  SHELL

end
