# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "dzmitry-lab/task02-2_lxc_in_debian10"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "debian10_with_lxc_vagrant_vm"
    vb.memory = "2048"
  end
end