---
#Playbook for task03-02 (Centos8 LXC - containers configuration)
- hosts: all
  connection: local
  become: true

  tasks:
    - name: SSH key pub copy
      set_fact:
        my_ssh_key: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"
      
    - name: Create containers
      lxc_container:
        name: "{{ inventory_hostname }}"
        container_log: true
        template: download
        state: started
        template_options:  --dist centos --release 8 --arch amd64
        container_command: |
          if [ ! -d ~/.ssh ]; then
          mkdir ~/.ssh
          echo "{{ lookup('file', my_ssh_key) }}" | tee -a ~/.ssh/authorized_keys
          fi
          echo "nameserver 10.0.3.1" > /etc/resolv.conf
          sed -i 's/dhcp/none/' /etc/sysconfig/network-scripts/ifcfg-eth0
          echo "IPADDR={{ ansible_host }}" >> /etc/sysconfig/network-scripts/ifcfg-eth0
          echo "PREFIX=24" >> /etc/sysconfig/network-scripts/ifcfg-eth0
          echo "GATEWAY=10.0.3.1" >> /etc/sysconfig/network-scripts/ifcfg-eth0
          echo "DNS1=10.0.3.1" >> /etc/sysconfig/network-scripts/ifcfg-eth0
          systemctl restart NetworkManager.service
          sleep 5
          yum install -y sudo openssh-server httpd php python2
          alternatives --set python /usr/bin/python2
          systemctl start sshd

- hosts: all
  connection: local
  become: true
  tasks:

  - name: checking container key is up to date in known_hosts
    shell: sleep 10; ssh-keygen -R {{ ansible_host }}; (ssh-keyscan {{ ansible_host }} >> ~/.ssh/known_hosts)
  
  - name: copying web-files to all containers
    shell:
      cmd:  scp -r /vagrant/web/ root@{{ ansible_host }}:/var/www/

- hosts: all
  become: true
  tasks:
  - name: Ensure services are running and enabled
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
       - httpd
       - php-fpm
       
- hosts: centos1
  connection: local
  tasks:
  - name: copying apache conf-files to 1st container
    shell: scp /vagrant/apache_conf/01-demosite-static.conf root@{{ ansible_host }}:/etc/httpd/conf.d/

- hosts: centos2
  connection: local
  tasks:
  - name: copying apache conf-files to 2st container
    shell: scp /vagrant/apache_conf/01-demosite-php.conf root@{{ ansible_host }}:/etc/httpd/conf.d/
    
- hosts: all
  tasks:
  - name: restart httpd
    service: 
      name: httpd
      state: restarted
