---
#Playbook for task03-02 (LXC - containers configuration)
- hosts: all
  become: true
  tasks:
  - name: Install the items
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - httpd
      - php
        
  - name: Copy sites
    copy:
      src: /vagrant/web
      dest: /var/www/
      
  - name: Copy configs to centos1
    copy:
      src: /vagrant/apache_conf/01-demosite-static.conf
      dest: /etc/httpd/conf.d/
    delegate_to: centos1

  - name: Copy configs to centos2
    copy:
      src: /vagrant/apache_conf/01-demosite-php.conf
      dest: /etc/httpd/conf.d/
    delegate_to: centos2

  - name: Restart apache
    service:
      name: httpd
      state: restarted
