version: "3"
services:

  jenkins:
    build: jenkins/
    networks:
      app_net:
        ipv4_address: 192.168.5.10
    ports:
      - 80:8080

  nexus:
    build: nexus/
    networks:
      app_net:
        ipv4_address: 192.168.5.11
    ports:
      - 81:8081

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24