# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos8"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define "slave1" do |slave|
    slave.vm.hostname = "slave1.puppet"
    slave.vm.network "private_network", ip: "192.168.4.11"
	slave.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  end
  
  config.vm.define "slave2" do |slave|
    slave.vm.hostname = "slave2.puppet"
    slave.vm.network "private_network", ip: "192.168.4.12"
    slave.vm.network "forwarded_port", guest: 80, host: 8081, host_ip: "127.0.0.1"
  end

  config.vm.define "master", primary: true do |master|
    master.vm.hostname = "master.puppet"
    master.vm.network "private_network", ip: "192.168.4.10"
    master.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
	  ansible.become = true
      ansible.inventory_path = "./inventory"
	  ansible.limit = 'all'
    end
  end

end