---
#Playbook for task06 (jenkins)
- name: jenkins provision
  hosts: jenkinses
  connection: local
  tasks:
  - import_role:
      name: jenkins
      
  - name: Checking container key is up to date in known_hosts
    become_user: vagrant
    shell: ssh-keyscan {{ item }} >> ~/.ssh/known_hosts
    loop:
      - '192.168.5.11'
      - '192.168.5.12'
      - '192.168.5.13'

- name: nodes provision
  hosts: nodes
  gather_facts: no
  tasks:
  - name: Ensure needed packages are installed.
    dnf:
      name: "{{ item }}"
      disable_gpg_check: yes
      state: present
    loop:
      - java-1.8.0-openjdk
      - jq
      
  - name: Include production role (service wordcloud creation)
    include_role: 
      name: production
    when: inventory_hostname == "production"
     
- name: nexus provision
  hosts: nexuses
  become: true
  pre_tasks:
  - name: Ensure needed packages are installed.
    dnf:
      name: java-1.8.0-openjdk
      disable_gpg_check: yes
      state: present

  vars:
    nexus_admin_password: "admin"
    nexus_config_maven: false
    nexus_config_raw: true
    nexus_repos_raw_hosted:
      - name: word-cloud-builds
        strict_content_validation: false
        version_policy: release
        write_policy: allow
    nexus_roles:
      - id: wcg-uploaders
        name: wcg-uploaders
        description: wcg-uploaders
        privileges:
          - nx-repository-view-*-*-edit
        roles: []
      - id: wcg-downloaders
        name: wcg-downloaders
        description: wcg-downloaders
        privileges:
          - nx-repository-view-*-*-read
        roles: []
    nexus_local_users:
      - username: uploader
        state: present
        first_name: uploader
        last_name: uploader
        email: support@company.com
        password: "uploader"
        roles:
          - wcg-uploaders
      - username: downloader
        state: present
        first_name: downloader
        last_name: downloader
        email: support@company.com
        password: "downloader"
        roles:
          - wcg-downloaders

  roles:
    - role: ansible-thoteam.nexus3-oss