# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "dzmitry-lab/task02-1_centos8"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos8_ansible_vagrant_vm"
    vb.memory = "512"
  end
# Provisioning configuration for Ansible.
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "centos8_lamp.yaml"
	ansible.become = true
 end
end
